---
title: "STA6257_Project_LSTM_Time_Series"
author: "Gaurav Kesireddy"
date: '`r Sys.Date()`'
format:
  html:
    code-fold: true
course: STA 6257 - Advance Statistical Modeling
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
editor: 
  markdown: 
    wrap: 72
---

## Introduction

The LSTM model is a powerful recurrent neural system specially designed
to overcome the exploding / vanishing gradient problems that typically
arise when learning long-term dependencies, even when the minimal time
lags are very long. Overall, this can be prevented by using a constant
error carousel (CEC), which maintains the error signal within each
unit's cell. As a matter of fact, such cells are recurrent networks
themselves, with an interesting architecture in the way that the CEC is
extended with additional features, namely the input gate and output
gate, forming the memory cell. The self-recurrent connections indicate
feedback with a lag of one time step. Cite this paper [@LSTMreview].

## Methods

## Analysis and Results

### Data and Visualisation

### Statistical Modeling

### Conclusion

## References
